language: node_js
node_js:
  - "8"
  - "9"

addons:
  mariadb: '10.2'

cache: yarn
script:
  - bin/opla init --non-interactive --database-name opla_test
  - mysql -e 'CREATE DATABASE opla_test;'
  - yarn db-migrate up
  - yarn lint
  - yarn test
