_test_script: &nodetest #YAML anchors are a hack cause travis stages does not yet support matrix expansion : https://github.com/travis-ci/beta-features/issues/28
  language: node_js
  addons:
    mariadb: '10.2'
  cache: yarn
  script:
    - mysql -e 'CREATE DATABASE opla_test;'
    - bin/opla init --non-interactive --database-name opla_test
    - bin/opla migrations up
    - yarn lint
    - yarn test

jobs:
  include:
    - stage: test
      <<: *nodetest 
      node_js: '8'

    - stage: test
      <<: *nodetest 
      node_js: '9'

    - stage: publish
      language: ruby
      provider: script
      services:
        - docker
      script: ./travis/publish.sh

    - stage: "deploy to QA :rocket:"
      language: ruby
      services:
        - docker
      env:
        - GCLOUD_CLUSTER_ID=qa
        - GCLOUD_CLUSTER_ZONE=europe-west1-b
        - COMMIT_ID=$TRAVIS_COMMIT
        - K8S_ENV=qa
        #CLIENT_ID
        - secure: "Svokit5r4ePAznisSJKF6E+KCXRCfTkEbMFjHnFdRvPwlSAiGgjth+FuO4hcq+SsNLv3HMyM5OO7co/u2WYbh/YYg+zp1j511mVYfOAlSRoZRRvT5Gs5o5KcNRdoCTttHFlW/l75JHZlBDi3YGcm8L2qsH52kQ9oTmW/F9Ve8Dx3KavnY/yew8NjcM/o0cDDBXOc1rKZ9Jc82p91HbCXE4oSs8SuSkcqu2fxwkDvkoiSPAhLpob5YRpe2MgXYP/p7GpR4bgZgwxQDMrqD7ZF09/K8xdDxs7h4N6k1SdulVptPVu5w0KWHvaBuXbklDRQAYdmBXpSgE5qj1X/tJJUE6mNlJGiwt0LR49X2IHAtcZZBKWpptY0eqtbB8FiLro27Zfrt+NWf8gNQvYqMotgCZD8Q/ODpZEmGHzJ8ZX7xb7+ZyDTPd5git+hAFTxqavsK+kUNLV8Qn7ghDKtM1Qiw3u4gasWurU7U19TgBMmxMcW2HqJhx7D39f3akpUO4X48+bf0rfIhF4r3jg/h44LdsnxecHwZbmGLZfbdjePhcKHZETLzw0YmtqeobdxgjjftoyH9o5ILd02Qx5NQ9emZFmWyU6yfTHfhJRcMLEI7ViMeChzRumYQxg2oyPzZRzVswfwHaWjgzvJlUXxBT3dcKHVFE6PySHZlwTQD5S+Zko="
        #CLIENT_SECRET
        - secure: "fUqlDsUX0er/lWhdgqXahuUNQBgNs2AVZkbINY6DoGQPCB33V8Kvx1SFAwxMWSPtxXk7g70iB/Uk2TiYYeJVzCH4tV7S8zi+If4undXzd3SRFE/HPGXItjlXx5jO4ew5H5xqnGbKAlF+WhrdSmh98Re2w2MLKtRfQrc1xXWy45OjHlQfG+F3VzPOV3FtO56wLoMbuFwZvDseOCD71EpYI7LVC+fl0a+SK3DVzZBuR9Ka6pNGifhXW80E7N12DflkTb/lTULrJpGJNPafGRIIbLG+bGKlPAHyaxaYL3DOkMvZB3gkhOs8Rz7H4J8FqKT4Mo3rfQEPfOkvcXqP+djdK3aVVo7zuZpY7FTPpmiKNRfHAkhEnbggJRBLvGMEgV+umOrE5mUHet2oLS5h0pAxCN+JrEH5F9b/YpHR5nS99qokLodYHgcYUlsm27+WwuNppeynLQob2laSKeCoA5JViYUJ7ep7kjsQVN+nczMhUEpr8u1EnsHwfcfB0HGoGB4FQSECBz5+XB2d5seAkLkE11VoCxye1f9yckfMU+6U/W/Fxml+6ynY4jc5GqjxsvZ/Yv3l3Fw6BfvCBLV9rXdzLMBjrF9VcfBhwGxO3v+PrFg9nABiu8WYUdybPVBiadOk9tw7eVBYL6jWoN387UQoTp0Gm3Iu8Ou+m3c3tIJsAXg="
        #GCLOUD_PROJECT_ID
        - secure: "d6YBZTYySzhpovI8rvSnjOjrBwOPyZGo+69r32fDrhAv85xLHyVWb9yTPtUGlr70amhMdw3eypxlvGIFt5m1AD63pjXfSUcZDd4jGGTJl8U6EGATfOmXUPu1ulsAuf3mBScTBx+70xGCCB2vbhCrBX/kP76iWoIefxf4YTH6Uhaq10mzy+FsFHdo8bWcJ1eI24/defIb7Vs98+ZOzjYAtPL34HiaPel7pUH3+8hzdUtX+TsZ8vvE9CZfEcPDBUGLH1ZRVBpYXDXioAvY4nWkz8nV3m7IJO1RvIEFRAAJe6v5opxGvPkKE1p/6XcgkIHDQjYdtxQQiheJVbaW0kX/fbf+nxKcxh38/Spy+IeXpq6RDRp4AKheQGItW0322wJMstftw1rK89e2nuRfEcE5qD2xEAalv4K1ndye/Y6LcGkhDXf0B8W3Nmn7ixJ8EpXzqTzw7AjVR7CKmitHImlpAVEKDOLqhYxKf5zu10LWalgQHQSvYOscpFOWtADeArAMRo+uO7d4p7y+fC4VBV79j+4BdI1QwgoXsnHjcnX05ZEOqbt3YCK3Ag272A00T+xRm82JblqAaLFKsoji2gkks+x1E9DqZqJ3xn1f/GBCPubUMQBsJxxaoLWKz/pc3H3WQiJMPJchdqw+uywwH+TZgYWWEMmR6V5BQrfxD3nvqHY="
        #API_DOMAIN
        - secure: "jSNxvGs53lUwaNxPUVk+g2bSezIzVlWVDCPceTb6To2DyItQlq0X8jqpFbp+uCUzoPpdg0jS1G+xjDXcB5eLNILh1rSZMCccz9IUc0UP/SgpXTBHNg5WMwEbffO3oPelAPztcN7Q4C72pq/z5mFCtSaIpuVzJJxp3dwK9gpzmRhKo1I8mk3dqUtzeBx2kAWNdHUbqLx1xpwN9aZ16G+w9ZRfbALpFq4O26AZgpWaQWudkPX1gj3H/95GGhNJpiQNIv/oQj3fDNkdcO7ru1liiGhgh28TFSgKoHM142QQ3G5WoWkWDTan6uqsITnAkFTtbRT2+p47U6iuFY+xPv+pzIyB325+mAvSGM22xrxvtITSUfmCsiIh1jVrl+hxNnUSEPhQQi+smNa6Hvms/7pxo5Ef9ZNTMsajBexD+dMrqgRv4DbX9QO23Qv25NsPvjH86EY34DmAYMsXmiRatYpEUn1T4mdGUt9Z7fyOZEOEnfyVWp2Q92qxup4cDBG6cw+nKvuxjWpXhCWMVQVIyZjYVqTxSUJO7nE2u6eHkjfLjoYWKKYJMHn/2ZifkfmX2GLw1ZJGpKbagJ5VGDLGN4q9iRASLviuj74PN1TDXZzmz67WP8ZNRO66jR/aoXm20YNiuiXTQeseo77bjmpvG+94Lldt3eB77fdy1m3HsWKR+cU="
      if: type IN (push) and branch in (master, feature/dockerfile)
      install: ./travis/setup_k8s.sh
      script: make deploy

stages:
  - test
  - publish 
  - "deploy to QA :rocket:"

env:
  global:
    #DOCKER_USER
    - secure: "iJCfaGKfvNpwJTEiX+k03j8Jmnw543jEMqq8z9vilRHCil19brmYguhFrw6zNC/P3iJYIfGrLnqNplZs4sIaGcz1xCL5aHq7TuS6bJAm7G5ZBqBhghAowPkYnfSBGoK8h/N8awXjo2Wucx0Cq6et6JXJdiq72YPtmt/w8XFC6iHfgECgn73Z4uFgXymVEPSTJpqbLp2c9sRQg1xJJG+/Lp6f5emkEYDvA9In/4KziPTOZjBHYPq17prU0RjLXpT3T7N0JariAS2gjiTr2V4LrS/yt7qaHOOt5wQ9XqeKFIFklszsgaob0g1lgqLbW+YfnZnhHDTz0137RQ9tSS92zRBl/yb9lg16DmEA/OepJ/vAw1uRmMrUDRT6ZtuGMlaV/NzH8AUdY8xn0/tTvnJQbeZdHQ+y9195Qs/XSH0ultOqNeyRv7xlnqzw/X1uypAphiLeOPRF12KJn/HUVlGUzjuPod9alRNj7oP2ZIeDAVG9gzhxdQKJYLgfWEM8iM3Ax4WcUfECLpF3riOTgboWpMJE2x5WSHWWq7V6pzKpV8o7wxxSe80cjdBytlrhgT/htmoQa+UE0DH9iz3T+QhRW2+EOkQ6CwgLq7aop4p1xJEJYGKN4iPmPOq0ppHg6QLSRmK2iGqZ0h454u7J3Bt81XU2O4HBPBIO4gfzqFQ0LzY="
    #DOCKER_PASS
    - secure: "RNs4iBnBBC3jy9FexjZtJ71j3ZLEiICqXe0uNoCEVwU7quf9gMrkPbLjX0qGAeMGcGwWR+fAGH9GWQOZuFSJNmzrHCjitZN/AiHCqeVXRGzPyTtnb/yd4r1DvRawlnNrFLWqmF9rcjaJKiIiY+W2tTDNEjurrLlLLxzXC8QeyIHP9rfzGoxc3qQ+bWWsG800AJPAAxnXiFWkGCVIBcDQPqVCA03/8XScJaaO/sXodxqmuNYdB4BL2rImmOin3a38B8sAhBKMwDcRAMgypdaQX7y1cbJtoIe0twoPJlL/nFa2Dy2D7PY8LZxjKQYG5SkJZQO3MNN1ipUjKvw164EErDbqoY8YdFFQTbN+4cjbcNxtRvGmqVYxEtjmVNv4xSR0fKeTHtviIt+mmBVfRdsSJLXEm2rm5k2BVoH/j5wi+cP2zMm2zAubtjfl+0ivaMeHEJOYpXyiEYe5tnNWAI1MCE0TtB6LUf9QGiRih0c2QBkx9/W/8NmiedjEt0ujImFt89cf8xzq4UqVTvOYnV7vlfkvtHZbgwaebvuFJvg1EpicUmHlY1YNZcYbJkJQxSZR96Hp/zHGqy/bMCOS8tWw7ayQ9aHq4LyUDe65+cMvRf5pSrfxhpqB9KpdSA855dsYmzMdx5NHeQ7voQ5qoZySk3zVvkgF97j200tj5Rabn4o="
