---
kind: Service
apiVersion: v1
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8081

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: node
        image: opla/backend:{{ .Values.image.tag }}
        ports:
        - containerPort: 8081
        - containerPort: 9229
        env:
        - name: OPLA_BACKEND_DATABASE_HOST
          value: "db"
        - name: OPLA_BACKEND_DATABASE_PORT
          value: "3306"
        - name: OPLA_BACKEND_DATABASE_NAME
          value: opla_dev
        - name: OPLA_BACKEND_DATABASE_USER
          value: opla
        - name: OPLA_BACKEND_DATABASE_PASS
          value: foo
        - name: PORT
          value: "8081"
        - name: SKIP_MIGRATION
          value: "true"

--- 
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: backend-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"
spec:
  rules:
  - host: {{ .Values.api.domain }}
    http:
      paths:
      - path: /api
        backend:
          serviceName: backend
          servicePort: 80
      - path: /auth
        backend:
          serviceName: backend
          servicePort: 80
  tls:
    - secretName: {{ .Values.api.domain | replace "." "-" }}-tls
      hosts:
        - {{ .Values.api.domain }}
