---
project: helm

env:
  GITHUB_PAGES_BRANCH: gh-pages

tasks:
  _publish_charts:
    cmd: |-
      export SOURCE_DIR=$(pwd)
      export TMP_DIR=/tmp/helm-$(uuidgen)
      mkdir -p $TMP_DIR
      cd $TMP_DIR
      mkdir newchart
      git clone --depth 1 -b "{{.GITHUB_PAGES_BRANCH}}" "git@github.com:{{.GITHUB_PAGES_REPO}}.git" .
      helm package --version {{.CHART_VERSION}} $SOURCE_DIR/$CHART_DIR --destination newchart/
      helm repo index newchart/ --merge index.yaml
      mv newchart/* .
      rm -r newchart
      git add .
      git commit -m"{{.APPLICATION_NAME}}"
      git push origin $GITHUB_PAGES_BRANCH
