---
project: helm

env:
  GITHUB_PAGES_BRANCH: gh-pages

tasks:
  _publish:
    cmd: |-
      export SOURCE_DIR=$(pwd)
      export TMP_DIR=/tmp/helm-$(uuidgen)
      mkdir -p $TMP_DIR
      cd $TMP_DIR
      git clone --depth 1 -b "{{.GITHUB_PAGES_BRANCH}}" "git@github.com:{{.GITHUB_PAGES_REPO}}.git" .
      helm package --version 0.1.0-{{.COMMIT_SHA}} $SOURCE_DIR/$CHART_DIR
      helm repo index .
      git add .
      git commit -m"{{.APPLICATION_NAME}}"
      git push origin $GITHUB_PAGES_BRANCH
